name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DENO_VERSION:
          - v1.2.2
          - v1.x
        DB_VERSION:
          - mysql:5.5
          - mysql:5.6
          - mysql:5.7
          - mysql:8
          - mysql:latest
          - mariadb:5.5
          - mariadb:10.2
          - mariadb:10.3
          - mariadb:10.4
          - mariadb:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Deno ${{ matrix.DENO_VERSION }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.DENO_VERSION }}
      - name: check fmt
        run: deno fmt --check
      - name: Start ${{ matrix.DB_VERSION }}
        run: |
          sudo mkdir -p /var/run/mysqld/tmp
          sudo chmod -R 777 /var/run/mysqld
          docker container run --rm -d -p 3306:3306 \
            -v /var/run/mysqld:/var/run/mysqld \
            -v /var/run/mysqld/tmp:/tmp \
            -e MYSQL_ALLOW_EMPTY_PASSWORD=true \
            ${{ matrix.DB_VERSION }}
          ./.github/workflows/wait-for-mysql.sh
      - name: Run tests (TCP)
        run: |
          deno test --allow-env --allow-net=127.0.0.1:3306 ./test.ts
      - name: Run tests (--unstable) (UNIX domain socket)
        run: |
          SOCKPATH=/var/run/mysqld/mysqld.sock
          if [[ "${{ matrix.DB_VERSION }}" == "mysql:5.5" ]]; then
            SOCKPATH=/var/run/mysqld/tmp/mysql.sock
          fi
          DB_SOCKPATH=$SOCKPATH TEST_METHODS=unix \
            deno test --unstable --allow-env --allow-net=127.0.0.1:3306 \
            --allow-read=/var/run/mysqld/ ./test.ts
      - name: Install Deno 1.2.2
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.2.2