name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DB_VERSION:
          - mysql:5.5
          - mysql:5.6
          - mysql:5.7
          - mysql:8
          - mysql:latest
          - mariadb:5.5
          - mariadb:10.2
          - mariadb:10.3
          - mariadb:10.4
          - mariadb:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.2
      - name: check fmt
        run: deno fmt --check
      - name: test ts
        run: |
          docker run -d -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=true ${{ matrix.DB_VERSION }}
          ./.github/workflows/wait-for-mysql.sh
          deno test --allow-all ./test.ts
